CREATE INDEX T24LIVE.IX_FBNK_LIMIT_C103 ON T24LIVE.FBNK_LIMIT
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c103'),'^A'))
LOGGING
TABLESPACE INDEXT24LIVE
PCTFREE    10
INITRANS   2
MAXTRANS   167
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_LIMIT_C100 ON T24LIVE.FBNK_LIMIT
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c100'),'^A'))
LOGGING
TABLESPACE INDEXT24LIVE
PCTFREE    10
INITRANS   2
MAXTRANS   167
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;