/*--====================Optimize enq: HW - contention wait event  --> restart DB
ALTER SYSTEM SET EVENT = '44951 TRACE NAME CONTEXT FOREVER, LEVEL 1024' SCOPE=SPFILE sid='*';


--=======================COB DR
alter system set log_archive_config='dg_config=(t24r14dr,t24r14dc,cobr14dr,cobr14dc)' scope=both;

=====================================COB DR datafile
FRACOBR14_DR/COBR14DR/DATAFILE/DATAT24LIVE.407.943155183
FRACOBR14_DR/COBR14DR/DATAFILE/DATAT24LIVE.833.943155899
FRACOBR14_DR/COBR14DR/DATAFILE/HOMEBANKING_TBS.264.943153719

BACKUP AS COPY DATAFILE '+FRACOBR14_DR/COBR14DR/DATAFILE/DATAT24LIVE.407.943155183'   FORMAT   '+COBR14_DR';
BACKUP AS COPY DATAFILE '+FRACOBR14_DR/COBR14DR/DATAFILE/DATAT24LIVE.833.943155899'   FORMAT   '+COBR14_DR';
BACKUP AS COPY DATAFILE '+FRACOBR14_DR/COBR14DR/DATAFILE/HOMEBANKING_TBS.264.943153719'   FORMAT   '+COBR14_DR';

SWITCH DATAFILE '+FRACOBR14_DR/COBR14DR/DATAFILE/DATAT24LIVE.407.943155183' TO COPY;
SWITCH DATAFILE '+FRACOBR14_DR/COBR14DR/DATAFILE/DATAT24LIVE.833.943155899' TO COPY;
SWITCH DATAFILE '+FRACOBR14_DR/COBR14DR/DATAFILE/HOMEBANKING_TBS.264.943153719' TO COPY;

cd +FRACOBR14_DR/COBR14DR/DATAFILE
rm DATAT24LIVE.407.943155183
rm DATAT24LIVE.833.943155899
rm HOMEBANKING_TBS.264.943153719
*/
===============================================================================
--===========SWITCH OVER --DRP
===============================================================================
###primary
SELECT SWITCHOVER_STATUS FROM V$DATABASE;  -- TO STANDBY 
--If listener of standby is notstarted, the switchover status: "FAILED DESTINATION" --> start the standby's listener , the status change to "TO STANDBY".

alter system archive log current;

ALTER DATABASE COMMIT TO SWITCHOVER TO PHYSICAL STANDBY WITH SESSION SHUTDOWN; --from 11.2.0.4, after this step don't need shutdown DB
SHUTDOWN abort;
STARTUP MOUNT;

###standby
SELECT SWITCHOVER_STATUS FROM V$DATABASE; -- TO_PRIMARY / SESSIONS ACTIVE 
ALTER DATABASE COMMIT TO SWITCHOVER TO PRIMARY WITH SESSION SHUTDOWN;
ALTER DATABASE OPEN read write;
-> restart
alter system set log_archive_dest_state_11=enable sid='*';
alter system set log_archive_dest_state_12=enable sid='*';
alter system set log_archive_dest_state_13=enable sid='*';

###primary
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;


--====================SPLIT Partition 
alter session force parallel dml parallel 24;
alter session force parallel query parallel 24;

create table T24LIVE.FBNK_STMT_ENTRY_MAX 
as 
select /*+ parallel(t,24)*/ * from T24LIVE.FBNK_STMT_ENTRY where  recid like 'F%' ;
  --Elapsed: 00:30:00.07 - parallel 4 
  
select count(*) from T24LIVE.FBNK_STMT_ENTRY where  recid like 'F%' ;

delete T24LIVE.FBNK_STMT_ENTRY t where recid like 'DUMMY.%';
delete T24LIVE.FBNK_STMT_ENTRY t where recid ='?' ;
commit;
delete T24LIVE.FBNK_STMT_ENTRY t where recid like 'F%'; 
commit;
--Elapsed: 00:03:32.44

--ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18019') INTO (PARTITION STMT_ENTRY_P1704,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
--Elapsed: 00:01:22.25

select count(*) from T24LIVE.FBNK_STMT_ENTRY  PARTITION (STMT_ENTRY_PMAX_TMP1) where recid >'18050'

---ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18050') INTO (PARTITION STMT_ENTRY_P1705,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;


ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18080') INTO (PARTITION STMT_ENTRY_P1706,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18111') INTO (PARTITION STMT_ENTRY_P1707,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18142') INTO (PARTITION STMT_ENTRY_P1708,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;

ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18172') INTO (PARTITION STMT_ENTRY_P1709,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18203') INTO (PARTITION STMT_ENTRY_P1710,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18233') INTO (PARTITION STMT_ENTRY_P1711,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18264') INTO (PARTITION STMT_ENTRY_P1712,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;

ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18295') INTO (PARTITION STMT_ENTRY_P1801,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18323') INTO (PARTITION STMT_ENTRY_P1802,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18354') INTO (PARTITION STMT_ENTRY_P1803,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18384') INTO (PARTITION STMT_ENTRY_P1804,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18415') INTO (PARTITION STMT_ENTRY_P1805,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18445') INTO (PARTITION STMT_ENTRY_P1806,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18476') INTO (PARTITION STMT_ENTRY_P1807,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18507') INTO (PARTITION STMT_ENTRY_P1808,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18537') INTO (PARTITION STMT_ENTRY_P1809,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18568') INTO (PARTITION STMT_ENTRY_P1810,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18598') INTO (PARTITION STMT_ENTRY_P1811,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18629') INTO (PARTITION STMT_ENTRY_P1812,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES ;

ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18660') INTO (PARTITION STMT_ENTRY_P1901,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18688') INTO (PARTITION STMT_ENTRY_P1902,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18719') INTO (PARTITION STMT_ENTRY_P1903,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18749') INTO (PARTITION STMT_ENTRY_P1904,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18780') INTO (PARTITION STMT_ENTRY_P1905,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18810') INTO (PARTITION STMT_ENTRY_P1906,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18841') INTO (PARTITION STMT_ENTRY_P1907,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18872') INTO (PARTITION STMT_ENTRY_P1908,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18902') INTO (PARTITION STMT_ENTRY_P1909,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18933') INTO (PARTITION STMT_ENTRY_P1910,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18963') INTO (PARTITION STMT_ENTRY_P1911,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18994') INTO (PARTITION STMT_ENTRY_P1912,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE  INDEXES;

ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19025') INTO (PARTITION STMT_ENTRY_P2001,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19054') INTO (PARTITION STMT_ENTRY_P2002,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19085') INTO (PARTITION STMT_ENTRY_P2003,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19115') INTO (PARTITION STMT_ENTRY_P2004,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19146') INTO (PARTITION STMT_ENTRY_P2005,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19176') INTO (PARTITION STMT_ENTRY_P2006,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19207') INTO (PARTITION STMT_ENTRY_P2007,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19238') INTO (PARTITION STMT_ENTRY_P2008,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19268') INTO (PARTITION STMT_ENTRY_P2009,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19299') INTO (PARTITION STMT_ENTRY_P2010,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19329') INTO (PARTITION STMT_ENTRY_P2011,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19360') INTO (PARTITION STMT_ENTRY_P2012,PARTITION STMT_ENTRY_PMAX) UPDATE        INDEXES;

--//////////////////////////NEW
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19391') INTO (PARTITION STMT_ENTRY_P2101,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19419') INTO (PARTITION STMT_ENTRY_P2102,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19450') INTO (PARTITION STMT_ENTRY_P2103,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19480') INTO (PARTITION STMT_ENTRY_P2104,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19511') INTO (PARTITION STMT_ENTRY_P2105,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19541') INTO (PARTITION STMT_ENTRY_P2106,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19572') INTO (PARTITION STMT_ENTRY_P2107,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19603') INTO (PARTITION STMT_ENTRY_P2108,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19633') INTO (PARTITION STMT_ENTRY_P2109,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19664') INTO (PARTITION STMT_ENTRY_P2110,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19694') INTO (PARTITION STMT_ENTRY_P2111,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19725') INTO (PARTITION STMT_ENTRY_P2112,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19756') INTO (PARTITION STMT_ENTRY_P2201,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19784') INTO (PARTITION STMT_ENTRY_P2202,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19815') INTO (PARTITION STMT_ENTRY_P2203,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19845') INTO (PARTITION STMT_ENTRY_P2204,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19876') INTO (PARTITION STMT_ENTRY_P2205,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19906') INTO (PARTITION STMT_ENTRY_P2206,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19937') INTO (PARTITION STMT_ENTRY_P2207,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19968') INTO (PARTITION STMT_ENTRY_P2208,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19998') INTO (PARTITION STMT_ENTRY_P2209,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20029') INTO (PARTITION STMT_ENTRY_P2210,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20059') INTO (PARTITION STMT_ENTRY_P2211,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20090') INTO (PARTITION STMT_ENTRY_P2212,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20121') INTO (PARTITION STMT_ENTRY_P2301,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20149') INTO (PARTITION STMT_ENTRY_P2302,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20180') INTO (PARTITION STMT_ENTRY_P2303,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20210') INTO (PARTITION STMT_ENTRY_P2304,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20241') INTO (PARTITION STMT_ENTRY_P2305,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20271') INTO (PARTITION STMT_ENTRY_P2306,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20302') INTO (PARTITION STMT_ENTRY_P2307,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20333') INTO (PARTITION STMT_ENTRY_P2308,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20363') INTO (PARTITION STMT_ENTRY_P2309,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20394') INTO (PARTITION STMT_ENTRY_P2310,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20424') INTO (PARTITION STMT_ENTRY_P2311,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20455') INTO (PARTITION STMT_ENTRY_P2312,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20486') INTO (PARTITION STMT_ENTRY_P2401,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20515') INTO (PARTITION STMT_ENTRY_P2402,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20546') INTO (PARTITION STMT_ENTRY_P2403,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20576') INTO (PARTITION STMT_ENTRY_P2404,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20607') INTO (PARTITION STMT_ENTRY_P2405,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20637') INTO (PARTITION STMT_ENTRY_P2406,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20668') INTO (PARTITION STMT_ENTRY_P2407,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20699') INTO (PARTITION STMT_ENTRY_P2408,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20729') INTO (PARTITION STMT_ENTRY_P2409,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20760') INTO (PARTITION STMT_ENTRY_P2410,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20790') INTO (PARTITION STMT_ENTRY_P2411,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20821') INTO (PARTITION STMT_ENTRY_P2412,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20852') INTO (PARTITION STMT_ENTRY_P2501,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20880') INTO (PARTITION STMT_ENTRY_P2502,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20911') INTO (PARTITION STMT_ENTRY_P2503,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20941') INTO (PARTITION STMT_ENTRY_P2504,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('20972') INTO (PARTITION STMT_ENTRY_P2505,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21002') INTO (PARTITION STMT_ENTRY_P2506,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21033') INTO (PARTITION STMT_ENTRY_P2507,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21064') INTO (PARTITION STMT_ENTRY_P2508,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21094') INTO (PARTITION STMT_ENTRY_P2509,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21125') INTO (PARTITION STMT_ENTRY_P2510,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21155') INTO (PARTITION STMT_ENTRY_P2511,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('21186') INTO (PARTITION STMT_ENTRY_P2512,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE INDEXES;


--index unusable
SELECT owner, index_name
FROM dba_indexes
WHERE status = 'UNUSABLE';

SELECT index_owner, index_name, partition_name
FROM dba_ind_PARTITIONS
WHERE status = 'UNUSABLE';

SELECT index_owner, index_name, partition_name, subpartition_name
FROM dba_ind_SUBPARTITIONS
WHERE status = 'UNUSABLE';

insert /*+ parallel(t,24)*/ into T24LIVE.FBNK_STMT_ENTRY t
 select * from  T24LIVE.FBNK_STMT_ENTRY_MAX ;
commit;
 --Elapsed: 00:13:32.76 parallel 4
 
drop table T24LIVE.FBNK_STMT_ENTRY_MAX ;



--====================Online redefinition FBNK_ACCOUNT
select * from dba_lobs where table_name='FBNK_ACCOUNT'

select sum(bytes)/1024/1024/1024 from dba_segments where segment_name in ('SYS_LOB0000379407C00003$$','FBNK_ACCOUNT')
--110G
SELECT sum( s.bytes )/1024/1024/1024 FROM dba_indexes i, dba_segments s 
WHERE s.segment_name = i.index_name  AND   s.owner = i.owner AND   s.segment_type like 'INDEX%' 
and i.table_name='FBNK_ACCOUNT' and table_owner='T24LIVE'
--4G

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE('T24LIVE','FBNK_ACCOUNT',DBMS_REDEFINITION.CONS_USE_PK);
END;
/

--create table
CREATE TABLE T24LIVE.FBNK_ACCOUNT_INI
(
  RECID      VARCHAR2(255 BYTE),
  XMLRECORD  SYS.XMLTYPE
)
XMLTYPE XMLRECORD STORE AS CLOB (
  TABLESPACE  DATAT24LIVE
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  PCTVERSION  10
  CACHE
  )
NOCOMPRESS 
TABLESPACE DATAT24LIVE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    20
INITRANS   100
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARTITION BY HASH (RECID)
  PARTITIONS 128
  STORE IN (DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE,DATAT24LIVE)
CACHE
NOPARALLEL
MONITORING;

alter session force parallel dml parallel 32;
alter session force parallel query parallel 32;


BEGIN
DBMS_REDEFINITION.START_REDEF_TABLE('T24LIVE', 'FBNK_ACCOUNT','FBNK_ACCOUNT_INI',NULL,dbms_redefinition.cons_use_pk);
END;
/

------------
ORA-12008: error in materialized view refresh path
ORA-01555: snapshot too old: rollback segment number 514 with name
BEGIN
DBMS_REDEFINITION.ABORT_REDEF_TABLE('T24LIVE', 'FBNK_ACCOUNT','FBNK_ACCOUNT_INI');
END;
/

---------CHECK size
COLUMN SEGTYPE FORMAT A15
COLUMN SEGMENT FORMAT A35
COLUMN SIZEMB FORMAT 9999999
COLUMN TABLESPACE FORMAT A15

BREAK ON SEGTYPE SKIP 1 ON REPORT

COMPUTE SUM OF SIZEMB ON SEGTYPE
COMPUTE SUM OF SIZEMB ON REPORT

  SELECT SEGTYPE,
         SEG SEGMENT,
         SIZEMB,
         TABLESPACE_NAME TABLESPACE
    FROM (  SELECT '1-TABLE' SEGTYPE,
                   S.OWNER || '.' || S.SEGMENT_NAME SEG,
                   TRUNC (SUM (BYTES) / 1024 / 1024) SIZEMB,
                   S.TABLESPACE_NAME
              FROM DBA_SEGMENTS S
             WHERE     (   S.SEGMENT_NAME = UPPER ('&&segment')
                        OR S.SEGMENT_NAME LIKE UPPER ('&&segment#%'))
                   AND S.SEGMENT_TYPE LIKE 'TABLE%'
          GROUP BY S.OWNER || '.' || SEGMENT_NAME, TABLESPACE_NAME
          UNION
            SELECT '2-INDEX' SEGTYPE,
                   S.OWNER || '.' || S.SEGMENT_NAME SEG,
                   TRUNC (SUM (S.BYTES) / 1024 / 1024) SIZEMB,
                   S.TABLESPACE_NAME
              FROM DBA_SEGMENTS S, DBA_INDEXES I
             WHERE     S.SEGMENT_NAME = I.INDEX_NAME
                   AND S.SEGMENT_TYPE LIKE 'INDEX%'
                   AND S.OWNER = I.OWNER
                   AND (   I.TABLE_NAME = UPPER ('&&segment')
                        OR I.TABLE_NAME LIKE UPPER ('&&segment#%'))
          GROUP BY S.OWNER || '.' || S.SEGMENT_NAME, S.TABLESPACE_NAME
          UNION
            SELECT '3-LOBDATA' SEGTYPE,
                   L.COLUMN_NAME || ':' || S.OWNER || '.' || L.TABLE_NAME SEG,
                   TRUNC (SUM (S.BYTES) / 1024 / 1024) SIZEMB,
                   S.TABLESPACE_NAME
              FROM DBA_SEGMENTS S, DBA_LOBS L
             WHERE     S.SEGMENT_NAME = L.SEGMENT_NAME
                   AND (   S.SEGMENT_TYPE = 'LOBSEGMENT'
                        OR S.SEGMENT_TYPE LIKE 'LOB %')
                   AND S.OWNER = L.OWNER
                   AND (   L.TABLE_NAME = UPPER ('&&segment')
                        OR L.TABLE_NAME LIKE UPPER ('&&segment#%'))
          GROUP BY L.COLUMN_NAME || ':' || S.OWNER || '.' || L.TABLE_NAME,
                   S.TABLESPACE_NAME
          UNION
            SELECT '4-LOBINDEX' SEGTYPE,
                   L.COLUMN_NAME || ':' || S.OWNER || '.' || L.TABLE_NAME SEG,
                   TRUNC (SUM (S.BYTES) / 1024 / 1024) SIZEMB,
                   S.TABLESPACE_NAME
              FROM DBA_SEGMENTS S, DBA_LOBS L
             WHERE     S.SEGMENT_NAME = L.INDEX_NAME
                   AND S.SEGMENT_TYPE = 'LOBINDEX'
                   AND S.OWNER = L.OWNER
                   AND (   L.TABLE_NAME = UPPER ('&&segment')
                        OR L.TABLE_NAME LIKE UPPER ('&&segment#%'))
          GROUP BY L.COLUMN_NAME || ':' || S.OWNER || '.' || L.TABLE_NAME,
                   S.TABLESPACE_NAME)
ORDER BY SEGTYPE, SEG;

--monthend Elapsed: 19:40:54.04
--year16 : Elapsed: 28:44:54.24
--archive log on monthend 13*4G


CREATE UNIQUE INDEX T24LIVE.FBNK_ACCOUNT_PAR_PK_INI ON T24LIVE.FBNK_ACCOUNT_INI
(RECID) LOCAL
  TABLESPACE INDEXT24LIVE 
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.FBNK_ACCOUNT_PAR_PK_INI NOPARALLEL;

CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C1_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c1'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C1_INI NOPARALLEL;

CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C10_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c10'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C10_INI NOPARALLEL;

CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C143_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c143'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C143_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C163_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c163'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C163_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C20_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c20[not(@m)]'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C20_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C207_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c207'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C207_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C20_56_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c20[@m=56]'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C20_56_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C3_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c3'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C3_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C4_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c4'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C4_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C78_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c78'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C78_INI NOPARALLEL;


CREATE INDEX T24LIVE.IX_FBNK_ACCOUNT_C8_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c8'),'^A'))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.IX_FBNK_ACCOUNT_C8_INI NOPARALLEL;


CREATE INDEX T24LIVE.NIX_FBNK_ACCOUNT_C163_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL("T24LIVE"."NUMCAST"(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c163')),0))
TABLESPACE INDEXT24LIVE
PARALLEL ( DEGREE 16 INSTANCES 1 );

--ALTER UNIQUE INDEX T24LIVE.NIX_FBNK_ACCOUNT_C163_INI NOPARALLEL;


CREATE INDEX T24LIVE.NIX_FBNK_ACCOUNT_C2_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL("T24LIVE"."NUMCAST"(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c2')),0))
TABLESPACE INDEXT24LIVE
PARALLEL ( DEGREE 16 INSTANCES 1 );

--ALTER UNIQUE INDEX T24LIVE.NIX_FBNK_ACCOUNT_C2_INI NOPARALLEL;


CREATE INDEX T24LIVE.NIX_FBNK_ACCOUNT_C21_INI ON T24LIVE.FBNK_ACCOUNT_INI
(NVL("T24LIVE"."NUMCAST"(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c21')),0))
TABLESPACE INDEXT24LIVE
PARALLEL ( DEGREE 16 INSTANCES 1 );

--ALTER UNIQUE INDEX T24LIVE.NIX_FBNK_ACCOUNT_C21_INI NOPARALLEL;


CREATE INDEX T24LIVE.NIX_FBNK_ACCOUNT_PAR_ID_INI ON T24LIVE.FBNK_ACCOUNT_INI
("T24LIVE"."NUMCAST"("RECID"))
TABLESPACE INDEXT24LIVE
PARALLEL 24;

ALTER UNIQUE INDEX T24LIVE.NIX_FBNK_ACCOUNT_PAR_ID_INI NOPARALLEL;


ALTER TABLE T24LIVE.FBNK_ACCOUNT_INI ADD (
  CONSTRAINT FBNK_ACCOUNT_PAR_PK_INI
  PRIMARY KEY
  (RECID)
  USING INDEX LOCAL
  ENABLE NoVALIDATE);
  
-- start: 17:52:09 SQL>  end:18:48:05 SQL>
  
DECLARE
num_errors PLS_INTEGER;
BEGIN
DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS('T24LIVE','FBNK_ACCOUNT','FBNK_ACCOUNT_INI',0,TRUE, TRUE, TRUE, TRUE, num_errors);
END;
/

select object_name, base_table_name, ddl_txt from       DBA_REDEFINITION_ERRORS;
--Error---
ALTER TABLE "T24LIVE"."FBNK_ACCOUNT_INI" ADD CONSTRAINT "TMP$$_FBNK_ACCOUNT_PAR_PK0" PRIMARY KEY ("RECID")
  USING INDEX Local  ENABLE NOVALIDATE
----------
 
BEGIN 
DBMS_REDEFINITION.SYNC_INTERIM_TABLE('T24LIVE', 'FBNK_ACCOUNT', 'FBNK_ACCOUNT_INI');
END;
/

BEGIN
DBMS_REDEFINITION.FINISH_REDEF_TABLE('T24LIVE', 'FBNK_ACCOUNT', 'FBNK_ACCOUNT_INI');
END;
/

select 'alter '||type||' '||owner||'.'||name||' compile;'
FROM all_dependencies
WHERE upper("REFERENCED_NAME") ='FBNK_ACCOUNT'
---compile
alter VIEW T24LIVE.V_FBNK_ACCOUNT compile;
alter VIEW T24_LIVE_DWH.FBNK_ACCOUNT compile;
alter VIEW T24_LIVE_DWH.V_MBV_FBNK_ACCOUNT compile;
alter VIEW T24_LIVE_DWH.V_T24ACCOUNT compile;

--alter index
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C1_INI   MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C10_INI   MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C143_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C163_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C20_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C207_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C20_56_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C3_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C4_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C78_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.IX_FBNK_ACCOUNT_C8_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.NIX_FBNK_ACCOUNT_C163_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.NIX_FBNK_ACCOUNT_C2_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.NIX_FBNK_ACCOUNT_C21_INI  MONITORING USAGE;
ALTER INDEX T24LIVE.NIX_FBNK_ACCOUNT_PAR_ID_INI  MONITORING USAGE;

-----scan index function 

alter user t24live grant connect through thuyntm_dba;
login thuyntm_dba[t24live]

set line 200;
set timing on;
exec DBMS_MVIEW.REFRESH ('mv_user_indexes'); 
DECLARE
   CURSOR c IS SELECT column_expression, index_name FROM user_ind_expressions;
   rc   c%ROWTYPE;
BEGIN
   OPEN c;
   DELETE FROM mv_user_ind_expressions;
   LOOP
      FETCH c INTO rc;
      EXIT WHEN c%NOTFOUND;
      INSERT INTO mv_user_ind_expressions (column_expression, index_name)
           VALUES (rc.column_expression, rc.index_name);
   END LOOP;
   COMMIT;
END;
/


--====================Online redefinition FBNK_DEPO_WITHDRA
select sum(bytes)/1024/1024/1024 from dba_segments where segment_name in ('SYS_LOB0058131618C00003$$','FBNK_DEPO_WITHDRA')
--75G

SELECT sum( s.bytes )/1024/1024/1024 FROM dba_indexes i, dba_segments s 
WHERE s.segment_name = i.index_name  AND   s.owner = i.owner AND   s.segment_type like 'INDEX%' 
and i.table_name='FBNK_DEPO_WITHDRA' and table_owner='T24LIVE'
--1.5G

------//////////////
select recid from t24live.FBNK_DEPO_WITHDRA where recid not like 'BK%' and recid not like '1%'and recid not like 'CHG%'
and recid not like 'FX%' and recid not like 'MM%' and recid not like 'FT%' and recid not like 'TT%' and recid not like 'TRAN%'
and recid not like 'LD%' and recid not like 'DC%' and recid not like 'CCY%' and recid not like 'T1%'and recid not like 'VND%'
and recid not like 'USD%'
SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'BK%';

  COUNT(*)
----------
   4005226

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like '1%';

  COUNT(*)
----------
     24931

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'CHG%';

  COUNT(*)
----------
    169694

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'FX%';

  COUNT(*)
----------
      1443

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'MM%';

  COUNT(*)
----------
    196677

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'FT%'
  2  ;

  COUNT(*)
----------
     19661

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'TT%';

  COUNT(*)
----------
   8481669

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'TRAN%';

  COUNT(*)
----------
        10

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'LD%';

  COUNT(*)
----------
         9

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'DC%';

  COUNT(*)
----------
        12

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'CCY%';

  COUNT(*)
----------
        11

SQL> select count(*)  from t24live.FBNK_DEPO_WITHDRA where recid  like 'T1%';

  COUNT(*)
----------
        14
------//////////////

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE('T24LIVE','FBNK_DEPO_WITHDRA',DBMS_REDEFINITION.CONS_USE_PK);
END;
/

--//////////
CREATE TABLE T24LIVE.FBNK_DEPO_WITHDRA_INI
(
  RECID      VARCHAR2(255 BYTE),
  XMLRECORD  SYS.XMLTYPE
)
XMLTYPE XMLRECORD STORE AS CLOB (
  TABLESPACE  DATAT24LIVE
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  PCTVERSION  10
  CACHE
  )
TABLESPACE DATAT24LIVE
PARTITION BY range (RECID)
  (
partition DEPO_WITHDRA_2000 values less than ('12055') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2001 values less than ('12420') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2002 values less than ('12785') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2003 values less than ('13150') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2004 values less than ('13516') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2005 values less than ('13881') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2006 values less than ('14246') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2007 values less than ('14611') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2008 values less than ('14977') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2009 values less than ('15342') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2010 values less than ('15707') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2011 values less than ('16072') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2012 values less than ('16438') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2013 values less than ('16803') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2014 values less than ('17168') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2015 values less than ('17533') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2016 values less than ('17899') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2017 values less than ('18264') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2018 values less than ('18629') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2019 values less than ('18994') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2020 values less than ('19360') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2021 values less than ('19725') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2022 values less than ('20090') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2023 values less than ('20455') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2024 values less than ('20821') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_2025 values less than ('21186') tablespace DATAT24LIVE,
partition DEPO_WITHDRA_MAX values less than (MAXVALUE) tablespace DATAT24LIVE
  )
MONITORING;

--2014 con 2 ban ghi dang 17168

alter session force parallel dml parallel 16;
alter session force parallel query parallel 16;


BEGIN
DBMS_REDEFINITION.START_REDEF_TABLE('T24LIVE', 'FBNK_DEPO_WITHDRA','FBNK_DEPO_WITHDRA_INI',NULL,dbms_redefinition.cons_use_pk);
END;
/
--Elapsed: 03:34:05.45
--3.6h parallel 16

/*
CREATE UNIQUE INDEX T24LIVE.FBNK_DEPO_WITHDRA_P5_PK_INI ON T24LIVE.FBNK_DEPO_WITHDRA_INI
(RECID,vircol)
  TABLESPACE INDEXT24LIVE
LOGGING
LOCAL online
PARALLEL 16; 


CREATE INDEX T24LIVE.IX_FBNK_DEPO_WITHDRA_C29_INI ON T24LIVE.FBNK_DEPO_WITHDRA_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c29'),''))
LOGGING
TABLESPACE INDEXT24LIVE
PARALLEL 16;


CREATE INDEX T24LIVE.IX_FBNK_DEPO_WITHDRA_C34_INI ON T24LIVE.FBNK_DEPO_WITHDRA_INI
(NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c34'),''))
LOGGING
TABLESPACE INDEXT24LIVE
PARALLEL 16;


ALTER TABLE T24LIVE.FBNK_DEPO_WITHDRA_INI ADD (
  CONSTRAINT FBNK_DEPO_WITHDRA_P5_PK_INI
  PRIMARY KEY
  (RECID,vircol)
  USING INDEX LOCAL
  ENABLE noVALIDATE);

  alter INDEX T24LIVE.FBNK_DEPO_WITHDRA_P5_PK_INI noparallel;
  alter INDEX T24LIVE.IX_FBNK_DEPO_WITHDRA_C29_INI noparallel;
  alter INDEX T24LIVE.IX_FBNK_DEPO_WITHDRA_C34_INI noparallel;
  
*/

DECLARE
num_errors PLS_INTEGER;
BEGIN
DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS('T24LIVE','FBNK_DEPO_WITHDRA','FBNK_DEPO_WITHDRA_INI',DBMS_REDEFINITION.CONS_ORIG_PARAMS,TRUE, TRUE, TRUE, TRUE, num_errors);
END;
/
--Elapsed: 04:53:03.34
/*
CREATE UNIQUE INDEX T24LIVE.FBNK_DEPO_WITHDRA_P5_PK ON T24LIVE.FBNK_DEPO_WITHDRA
(RECID)
  TABLESPACE INDEXT24LIVE
LOGGING
LOCAL NOPARALLEL;

ALTER TABLE T24LIVE.FBNK_DEPO_WITHDRA ADD (
  CONSTRAINT FBNK_DEPO_WITHDRA_P5_PK
  PRIMARY KEY
  (RECID)
  USING INDEX LOCAL
  ENABLE VALIDATE);
*/
select object_name, base_table_name, ddl_txt from       DBA_REDEFINITION_ERRORS;
--Error-----
OBJECT_NAME                    BASE_TABLE_NAME                DDL_TXT
------------------------------ ------------------------------ --------------------------------------------------------------------------------
FBNK_DEPO_WITHDRA_P5_PK        FBNK_DEPO_WITHDRA              CREATE UNIQUE INDEX "T24LIVE"."TMP$$_FBNK_DEPO_WITHDRA_P5_0" ON "T24LIVE"."FBNK_
FBNK_DEPO_WITHDRA_P5_PK        FBNK_DEPO_WITHDRA              ALTER TABLE "T24LIVE"."FBNK_DEPO_WITHDRA_INI" ADD CONSTRAINT "TMP$$_FBNK_DEPO_WI
 
BEGIN 
DBMS_REDEFINITION.SYNC_INTERIM_TABLE('T24LIVE', 'FBNK_DEPO_WITHDRA', 'FBNK_DEPO_WITHDRA_INI');
END;
/

BEGIN
DBMS_REDEFINITION.FINISH_REDEF_TABLE('T24LIVE', 'FBNK_DEPO_WITHDRA', 'FBNK_DEPO_WITHDRA_INI');
END;
/
