=============================T24LIVE.FBNK_RE_C017  split partition
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18568') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1810,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18598') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1811,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18629') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1812,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18660') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1901,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18688') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1902,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18719') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1903,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18749') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1904,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18780') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1905,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18810') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1906,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18841') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1907,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18872') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1908,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18902') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1909,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18933') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1910,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18963') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1911,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('18994') INTO (PARTITION RE_CONSOL_SPEC_ENT_P1912,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19025') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2001,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19054') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2002,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19085') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2003,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19115') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2004,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19146') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2005,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19176') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2006,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19207') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2007,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19238') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2008,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19268') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2009,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19299') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2010,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19329') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2011,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19360') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2012,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19391') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2101,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19419') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2102,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19450') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2103,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19480') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2104,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19511') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2105,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19541') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2106,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19572') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2107,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19603') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2108,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19633') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2109,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19664') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2110,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19694') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2111,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19725') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2112,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19756') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2201,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19784') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2202,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19815') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2203,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19845') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2204,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19876') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2205,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19906') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2206,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19937') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2207,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19968') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2208,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('19998') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2209,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20029') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2210,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20059') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2211,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20090') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2212,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20121') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2301,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20149') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2302,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20180') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2303,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20210') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2304,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20241') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2305,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20271') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2306,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20302') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2307,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20333') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2308,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20363') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2309,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20394') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2310,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20424') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2311,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20455') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2312,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20486') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2401,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20515') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2402,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20546') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2403,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20576') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2404,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20607') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2405,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20637') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2406,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20668') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2407,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20699') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2408,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20729') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2409,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20760') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2410,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20790') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2411,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20821') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2412,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20852') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2501,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20880') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2502,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20911') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2503,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20941') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2504,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('20972') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2505,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21002') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2506,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21033') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2507,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21064') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2508,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21094') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2509,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21125') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2510,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21155') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2511,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;
ALTER TABLE T24LIVE.FBNK_RE_C017 SPLIT PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9 AT ('21186') INTO (PARTITION RE_CONSOL_SPEC_ENT_P2512,PARTITION RE_CONSOL_SPEC_ENT_PMAX_TMP9) ;

=============================FBNK_CATEG_ENTRY
select recid from t24live.FBNK_CATEG_ENTRY partition (CATEG_ENTRY_PMAX)
where recid not like '1%'

14:58:16 SQL> ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18629') INTO (PARTITION CATEG_ENTRY_P1812,PARTITION CATEG_ENTRY_PMAX) ;
 Table altered.
Elapsed: 00:04:41.28

09:51:09 SQL> ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18384') INTO (PARTITION CATEG_ENTRY_P1804,PARTITION CATEG_ENTRY_PMAX) ;
 Table altered.
Elapsed: 00:03:50.99

ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18384') INTO (PARTITION CATEG_ENTRY_P1804,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18415') INTO (PARTITION CATEG_ENTRY_P1805,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18445') INTO (PARTITION CATEG_ENTRY_P1806,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18476') INTO (PARTITION CATEG_ENTRY_P1807,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18507') INTO (PARTITION CATEG_ENTRY_P1808,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18537') INTO (PARTITION CATEG_ENTRY_P1809,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18568') INTO (PARTITION CATEG_ENTRY_P1810,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18598') INTO (PARTITION CATEG_ENTRY_P1811,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18629') INTO (PARTITION CATEG_ENTRY_P1812,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18660') INTO (PARTITION CATEG_ENTRY_P1901,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18688') INTO (PARTITION CATEG_ENTRY_P1902,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18719') INTO (PARTITION CATEG_ENTRY_P1903,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18749') INTO (PARTITION CATEG_ENTRY_P1904,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18780') INTO (PARTITION CATEG_ENTRY_P1905,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18810') INTO (PARTITION CATEG_ENTRY_P1906,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18841') INTO (PARTITION CATEG_ENTRY_P1907,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18872') INTO (PARTITION CATEG_ENTRY_P1908,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18902') INTO (PARTITION CATEG_ENTRY_P1909,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18933') INTO (PARTITION CATEG_ENTRY_P1910,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18963') INTO (PARTITION CATEG_ENTRY_P1911,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18994') INTO (PARTITION CATEG_ENTRY_P1912,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19025') INTO (PARTITION CATEG_ENTRY_P2001,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19054') INTO (PARTITION CATEG_ENTRY_P2002,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19085') INTO (PARTITION CATEG_ENTRY_P2003,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19115') INTO (PARTITION CATEG_ENTRY_P2004,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19146') INTO (PARTITION CATEG_ENTRY_P2005,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19176') INTO (PARTITION CATEG_ENTRY_P2006,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19207') INTO (PARTITION CATEG_ENTRY_P2007,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19238') INTO (PARTITION CATEG_ENTRY_P2008,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19268') INTO (PARTITION CATEG_ENTRY_P2009,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19299') INTO (PARTITION CATEG_ENTRY_P2010,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19329') INTO (PARTITION CATEG_ENTRY_P2011,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19360') INTO (PARTITION CATEG_ENTRY_P2012,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19391') INTO (PARTITION CATEG_ENTRY_P2101,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19419') INTO (PARTITION CATEG_ENTRY_P2102,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19450') INTO (PARTITION CATEG_ENTRY_P2103,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19480') INTO (PARTITION CATEG_ENTRY_P2104,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19511') INTO (PARTITION CATEG_ENTRY_P2105,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19541') INTO (PARTITION CATEG_ENTRY_P2106,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19572') INTO (PARTITION CATEG_ENTRY_P2107,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19603') INTO (PARTITION CATEG_ENTRY_P2108,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19633') INTO (PARTITION CATEG_ENTRY_P2109,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19664') INTO (PARTITION CATEG_ENTRY_P2110,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19694') INTO (PARTITION CATEG_ENTRY_P2111,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19725') INTO (PARTITION CATEG_ENTRY_P2112,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19756') INTO (PARTITION CATEG_ENTRY_P2201,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19784') INTO (PARTITION CATEG_ENTRY_P2202,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19815') INTO (PARTITION CATEG_ENTRY_P2203,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19845') INTO (PARTITION CATEG_ENTRY_P2204,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19876') INTO (PARTITION CATEG_ENTRY_P2205,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19906') INTO (PARTITION CATEG_ENTRY_P2206,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19937') INTO (PARTITION CATEG_ENTRY_P2207,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19968') INTO (PARTITION CATEG_ENTRY_P2208,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('19998') INTO (PARTITION CATEG_ENTRY_P2209,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20029') INTO (PARTITION CATEG_ENTRY_P2210,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20059') INTO (PARTITION CATEG_ENTRY_P2211,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20090') INTO (PARTITION CATEG_ENTRY_P2212,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20121') INTO (PARTITION CATEG_ENTRY_P2301,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20149') INTO (PARTITION CATEG_ENTRY_P2302,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20180') INTO (PARTITION CATEG_ENTRY_P2303,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20210') INTO (PARTITION CATEG_ENTRY_P2304,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20241') INTO (PARTITION CATEG_ENTRY_P2305,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20271') INTO (PARTITION CATEG_ENTRY_P2306,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20302') INTO (PARTITION CATEG_ENTRY_P2307,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20333') INTO (PARTITION CATEG_ENTRY_P2308,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20363') INTO (PARTITION CATEG_ENTRY_P2309,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20394') INTO (PARTITION CATEG_ENTRY_P2310,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20424') INTO (PARTITION CATEG_ENTRY_P2311,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20455') INTO (PARTITION CATEG_ENTRY_P2312,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20486') INTO (PARTITION CATEG_ENTRY_P2401,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20515') INTO (PARTITION CATEG_ENTRY_P2402,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20546') INTO (PARTITION CATEG_ENTRY_P2403,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20576') INTO (PARTITION CATEG_ENTRY_P2404,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20607') INTO (PARTITION CATEG_ENTRY_P2405,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20637') INTO (PARTITION CATEG_ENTRY_P2406,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20668') INTO (PARTITION CATEG_ENTRY_P2407,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20699') INTO (PARTITION CATEG_ENTRY_P2408,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20729') INTO (PARTITION CATEG_ENTRY_P2409,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20760') INTO (PARTITION CATEG_ENTRY_P2410,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20790') INTO (PARTITION CATEG_ENTRY_P2411,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20821') INTO (PARTITION CATEG_ENTRY_P2412,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20852') INTO (PARTITION CATEG_ENTRY_P2501,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20880') INTO (PARTITION CATEG_ENTRY_P2502,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20911') INTO (PARTITION CATEG_ENTRY_P2503,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20941') INTO (PARTITION CATEG_ENTRY_P2504,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('20972') INTO (PARTITION CATEG_ENTRY_P2505,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21002') INTO (PARTITION CATEG_ENTRY_P2506,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21033') INTO (PARTITION CATEG_ENTRY_P2507,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21064') INTO (PARTITION CATEG_ENTRY_P2508,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21094') INTO (PARTITION CATEG_ENTRY_P2509,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21125') INTO (PARTITION CATEG_ENTRY_P2510,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21155') INTO (PARTITION CATEG_ENTRY_P2511,PARTITION CATEG_ENTRY_PMAX) ;
ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('21186') INTO (PARTITION CATEG_ENTRY_P2512,PARTITION CATEG_ENTRY_PMAX) ;
 
 
 
 04:24:32 SYS@t24r14dr1 > ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY SPLIT PARTITION CATEG_ENTRY_PMAX AT ('18384') INTO (PARTITION CATEG_ENTRY_P1804,PARTITION CATEG_ENTRY_PMAX) ;

Table altered.

Elapsed: 00:01:02.44



FT_HIS_PMAX	MAXVALUE	8	DATAT24LIVE	DISABLED	10	174	0	4/17/2017 12:38:49 AM	0	0

STMT_ENTRY_PMAX	MAXVALUE	8	DATAT24LIVE	DISABLED	965260	69135	0	2/28/2018 12:47:43 AM	0	0


SELECT table_name, tab_type, del_range, pre_condition,post_condition,sub_type, hint_idx ,add_condition
          FROM sys.table_archive
          where table_name||sub_type||del_range not in 
 (select a.table_name||a.sub_type||a.del_range from sys.table_archive a,   sys.table_archive_log b
  where a.table_name||a.sub_type=b.table_name||b.tab_type
  and start_time <trunc(sysdate,'year')
  and numrow_del<1000000
  and archive_year like '%16')
  
  
=========================T24LIVE.FBNK_FUNDS_TRANSFER#HIS ================================
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21032') INTO (PARTITION FT_HIS_P2101,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21060') INTO (PARTITION FT_HIS_P2102,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21091') INTO (PARTITION FT_HIS_P2103,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21121') INTO (PARTITION FT_HIS_P2104,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21152') INTO (PARTITION FT_HIS_P2105,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21182') INTO (PARTITION FT_HIS_P2106,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21213') INTO (PARTITION FT_HIS_P2107,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21244') INTO (PARTITION FT_HIS_P2108,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21274') INTO (PARTITION FT_HIS_P2109,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21305') INTO (PARTITION FT_HIS_P2110,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21335') INTO (PARTITION FT_HIS_P2111,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT21366') INTO (PARTITION FT_HIS_P2112,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22032') INTO (PARTITION FT_HIS_P2201,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22060') INTO (PARTITION FT_HIS_P2202,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22091') INTO (PARTITION FT_HIS_P2203,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22121') INTO (PARTITION FT_HIS_P2204,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22152') INTO (PARTITION FT_HIS_P2205,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22182') INTO (PARTITION FT_HIS_P2206,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22213') INTO (PARTITION FT_HIS_P2207,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22244') INTO (PARTITION FT_HIS_P2208,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22274') INTO (PARTITION FT_HIS_P2209,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22305') INTO (PARTITION FT_HIS_P2210,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22335') INTO (PARTITION FT_HIS_P2211,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT22366') INTO (PARTITION FT_HIS_P2212,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23032') INTO (PARTITION FT_HIS_P2301,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23060') INTO (PARTITION FT_HIS_P2302,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23091') INTO (PARTITION FT_HIS_P2303,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23121') INTO (PARTITION FT_HIS_P2304,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23152') INTO (PARTITION FT_HIS_P2305,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23182') INTO (PARTITION FT_HIS_P2306,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23213') INTO (PARTITION FT_HIS_P2307,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23244') INTO (PARTITION FT_HIS_P2308,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23274') INTO (PARTITION FT_HIS_P2309,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23305') INTO (PARTITION FT_HIS_P2310,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23335') INTO (PARTITION FT_HIS_P2311,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT23366') INTO (PARTITION FT_HIS_P2312,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24032') INTO (PARTITION FT_HIS_P2401,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24061') INTO (PARTITION FT_HIS_P2402,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24092') INTO (PARTITION FT_HIS_P2403,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24122') INTO (PARTITION FT_HIS_P2404,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24153') INTO (PARTITION FT_HIS_P2405,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24183') INTO (PARTITION FT_HIS_P2406,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24214') INTO (PARTITION FT_HIS_P2407,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24245') INTO (PARTITION FT_HIS_P2408,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24275') INTO (PARTITION FT_HIS_P2409,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24306') INTO (PARTITION FT_HIS_P2410,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24336') INTO (PARTITION FT_HIS_P2411,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT24367') INTO (PARTITION FT_HIS_P2412,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25032') INTO (PARTITION FT_HIS_P2501,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25060') INTO (PARTITION FT_HIS_P2502,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25091') INTO (PARTITION FT_HIS_P2503,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25121') INTO (PARTITION FT_HIS_P2504,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25152') INTO (PARTITION FT_HIS_P2505,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25182') INTO (PARTITION FT_HIS_P2506,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25213') INTO (PARTITION FT_HIS_P2507,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25244') INTO (PARTITION FT_HIS_P2508,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25274') INTO (PARTITION FT_HIS_P2509,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25305') INTO (PARTITION FT_HIS_P2510,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25335') INTO (PARTITION FT_HIS_P2511,PARTITION FT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS SPLIT PARTITION FT_HIS_PMAX AT ('FT25366') INTO (PARTITION FT_HIS_P2512,PARTITION FT_HIS_PMAX) ;

=========================T24LIVE.FBNK_FUNDS_TRANSFER#HIS ================================
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21032') INTO (PARTITION TT_HIS_P2101,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21060') INTO (PARTITION TT_HIS_P2102,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21091') INTO (PARTITION TT_HIS_P2103,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21121') INTO (PARTITION TT_HIS_P2104,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21152') INTO (PARTITION TT_HIS_P2105,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21182') INTO (PARTITION TT_HIS_P2106,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21213') INTO (PARTITION TT_HIS_P2107,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21244') INTO (PARTITION TT_HIS_P2108,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21274') INTO (PARTITION TT_HIS_P2109,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21305') INTO (PARTITION TT_HIS_P2110,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21335') INTO (PARTITION TT_HIS_P2111,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT21366') INTO (PARTITION TT_HIS_P2112,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22032') INTO (PARTITION TT_HIS_P2201,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22060') INTO (PARTITION TT_HIS_P2202,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22091') INTO (PARTITION TT_HIS_P2203,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22121') INTO (PARTITION TT_HIS_P2204,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22152') INTO (PARTITION TT_HIS_P2205,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22182') INTO (PARTITION TT_HIS_P2206,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22213') INTO (PARTITION TT_HIS_P2207,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22244') INTO (PARTITION TT_HIS_P2208,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22274') INTO (PARTITION TT_HIS_P2209,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22305') INTO (PARTITION TT_HIS_P2210,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22335') INTO (PARTITION TT_HIS_P2211,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT22366') INTO (PARTITION TT_HIS_P2212,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23032') INTO (PARTITION TT_HIS_P2301,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23060') INTO (PARTITION TT_HIS_P2302,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23091') INTO (PARTITION TT_HIS_P2303,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23121') INTO (PARTITION TT_HIS_P2304,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23152') INTO (PARTITION TT_HIS_P2305,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23182') INTO (PARTITION TT_HIS_P2306,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23213') INTO (PARTITION TT_HIS_P2307,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23244') INTO (PARTITION TT_HIS_P2308,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23274') INTO (PARTITION TT_HIS_P2309,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23305') INTO (PARTITION TT_HIS_P2310,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23335') INTO (PARTITION TT_HIS_P2311,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT23366') INTO (PARTITION TT_HIS_P2312,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24032') INTO (PARTITION TT_HIS_P2401,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24061') INTO (PARTITION TT_HIS_P2402,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24092') INTO (PARTITION TT_HIS_P2403,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24122') INTO (PARTITION TT_HIS_P2404,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24153') INTO (PARTITION TT_HIS_P2405,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24183') INTO (PARTITION TT_HIS_P2406,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24214') INTO (PARTITION TT_HIS_P2407,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24245') INTO (PARTITION TT_HIS_P2408,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24275') INTO (PARTITION TT_HIS_P2409,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24306') INTO (PARTITION TT_HIS_P2410,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24336') INTO (PARTITION TT_HIS_P2411,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT24367') INTO (PARTITION TT_HIS_P2412,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25032') INTO (PARTITION TT_HIS_P2501,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25060') INTO (PARTITION TT_HIS_P2502,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25091') INTO (PARTITION TT_HIS_P2503,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25121') INTO (PARTITION TT_HIS_P2504,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25152') INTO (PARTITION TT_HIS_P2505,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25182') INTO (PARTITION TT_HIS_P2506,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25213') INTO (PARTITION TT_HIS_P2507,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25244') INTO (PARTITION TT_HIS_P2508,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25274') INTO (PARTITION TT_HIS_P2509,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25305') INTO (PARTITION TT_HIS_P2510,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25335') INTO (PARTITION TT_HIS_P2511,PARTITION TT_HIS_PMAX) ;
ALTER TABLE T24LIVE.FBNK_TELLER#HIS SPLIT PARTITION TT_HIS_PMAX AT ('TT25366') INTO (PARTITION TT_HIS_P2512,PARTITION TT_HIS_PMAX) ;