----===================================================


----===================================================
/*
---drop unusable
--T24LIVE	IX_FBNK_LIMIT_C103
  CREATE INDEX "T24LIVE"."IX_FBNK_LIMIT_C103" ON "T24LIVE"."FBNK_LIMIT" (NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c103'),'^A')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXT24LIVE" 
  ALTER INDEX "T24LIVE"."IX_FBNK_LIMIT_C103"  UNUSABLE
  
--T24LIVE	IX_FBNK_LIMIT_C100
  CREATE INDEX "T24LIVE"."IX_FBNK_LIMIT_C100" ON "T24LIVE"."FBNK_LIMIT" (NVL(EXTRACTVALUE(SYS_MAKEXML("SYS_NC00003$"),'/row/c100'),'^A')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXT24LIVE" 
  ALTER INDEX "T24LIVE"."IX_FBNK_LIMIT_C100"  UNUSABLE
*/
----===================================================
--INDEX GLOBAL
--table1
/*
  CREATE UNIQUE INDEX "T24LIVE"."FBNK_TELLER#HIS_PAR_PK_NEW" ON "T24LIVE"."FBNK_TELLER#HIS" ("RECID",'1') LOCAL ONLINE 
  TABLESPACE "DATAT24LIVE" parallel 28;
--Elapsed: 00:00:35.62
--Elapsed: 00:00:28.14
  
  alter table T24LIVE.FBNK_TELLER#HIS drop CONSTRAINT FBNK_TELLER#HIS_PAR_PK;
  
  drop index T24LIVE.FBNK_TELLER#HIS_PAR_PK;

  CREATE UNIQUE INDEX "T24LIVE"."FBNK_TELLER#HIS_PAR_PK" ON "T24LIVE"."FBNK_TELLER#HIS" ("RECID") LOCAL ONLINE 
  TABLESPACE "INDEXT24LIVE" parallel 28;
--Elapsed: 00:00:09.91
--Elapsed: 00:00:06.91

  
	
  ALTER TABLE T24LIVE.FBNK_TELLER#HIS ADD (
  CONSTRAINT FBNK_TELLER#HIS_PAR_PK
  PRIMARY KEY
  (RECID)
  USING INDEX T24LIVE.FBNK_TELLER#HIS_PAR_PK
  ENABLE NOVALIDATE);
alter index T24LIVE.FBNK_TELLER#HIS_PAR_PK noparallel;
  drop index T24LIVE.FBNK_TELLER#HIS_PAR_PK_NEW;
BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24LIVE'
     ,IndName        => 'FBNK_TELLER#HIS_PAR_PK'
    ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	,Degree          => 28);
END;
/
*/
----===================================================
-------------------------------------------------------
--table2 -----
--Golden gate
////////
/*
MAP T24LIVE.FBNK_STMT_ENTRY, target T24REP.J$FBNK_STMT_ENTRY -- bang khong co partition 
MAP T24LIVE.FBNK_STMT_ENTRY, target T24REP.J$FBNK_STMT_ENTRY_HBK -- bang khong co partition
MAP T24LIVE.FBNK_STMT_ENTRY, target T24REP.FBNK_STMT_ENTRY_HBK --5.8G - 1 partition

CREATE UNIQUE INDEX T24REP.FBNK_STMT_HBK_PAR_PK_NEW ON 
T24REP.FBNK_STMT_ENTRY_HBK (RECID,'1') local online TABLESPACE DWH_IND_TBS parallel 2;

ALTER TABLE T24REP.FBNK_STMT_ENTRY_HBK Drop  CONSTRAINT FBNK_STMT_HBK_PAR_PK;

drop index T24REP.FBNK_STMT_HBK_PAR_PK;

CREATE UNIQUE INDEX T24REP.FBNK_STMT_HBK_PAR_PK ON 
T24REP.FBNK_STMT_ENTRY_HBK (RECID) local online TABLESPACE DWH_IND_TBS parallel 2;

ALTER TABLE T24REP.FBNK_STMT_ENTRY_HBK ADD (  CONSTRAINT FBNK_STMT_HBK_PAR_PK
  PRIMARY KEY  (RECID)  USING INDEX T24REP.FBNK_STMT_HBK_PAR_PK  ENABLE noVALIDATE);
  
  alter index T24REP.FBNK_STMT_HBK_PAR_PK noparallel;

drop index T24REP.FBNK_STMT_HBK_PAR_PK_NEW;

BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24REP'
     ,IndName        => 'FBNK_STMT_HBK_PAR_PK'
     ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	 ,Degree          => 24);
END;
/
*/
///////
MAP T24LIVE.FBNK_STMT_ENTRY, target T24REP.FBNK_STMT_ENTRY --529G / split partition?
--T24REP	PACKAGE BODY	PKG_OGG_EXTRACT	VALID
/*
CREATE UNIQUE INDEX T24REP.FBNK_STMT_ENTRY_PAR_PK_N ON T24REP.FBNK_STMT_ENTRY (RECID,'1') local online 
TABLESPACE T24REP_TBS parallel 24;
--Elapsed: 00:45:14.58 --d2739fpmpqv4c FBNK_STMT_ENTRY_PARTITION_PK

ALTER TABLE T24REP.FBNK_STMT_ENTRY drop  CONSTRAINT FBNK_STMT_ENTRY_PARTITION_PK;

drop index T24REP.FBNK_STMT_ENTRY_PARTITION_PK;

CREATE UNIQUE INDEX T24REP.FBNK_STMT_ENTRY_PARTITION_PK ON T24REP.FBNK_STMT_ENTRY (RECID) local online 
TABLESPACE DWH_IND_TBS 
parallel 24;

ALTER TABLE T24REP.FBNK_STMT_ENTRY ADD (  CONSTRAINT FBNK_STMT_ENTRY_PARTITION_PK  PRIMARY KEY  (RECID)
  USING INDEX T24REP.FBNK_STMT_ENTRY_PARTITION_PK  ENABLE NOVALIDATE);
================
alter index T24REP.FBNK_STMT_ENTRY_PARTITION_PK noparallel;

drop index T24REP.FBNK_STMT_ENTRY_PAR_PK_N;

BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24REP'
     ,IndName        => 'FBNK_STMT_ENTRY_PARTITION_PK'
     ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	 ,Degree          => 24);
END;
/
*/

////////
T24REP.OGG_STMT_ENTRY
/*
--done CREATE UNIQUE INDEX T24REP.PK_OGG_STMT_ENTRY_ID_PK ON T24REP.OGG_STMT_ENTRY (STMT_ENTRY_ID,BOOKING_DATE) local online
TABLESPACE DWH_IND_TBS
PARALLEL 12;
--Elapsed: 00:08:26.81

ALTER TABLE T24REP.OGG_STMT_ENTRY Drop CONSTRAINT PK_OGG_STMT_ENTRY_ID;

ALTER TABLE T24REP.OGG_STMT_ENTRY ADD (
  CONSTRAINT PK_OGG_STMT_ENTRY_ID
  PRIMARY KEY
  (STMT_ENTRY_ID,BOOKING_DATE)
  USING INDEX T24REP.PK_OGG_STMT_ENTRY_ID_PK
  ENABLE NOVALIDATE);
  */
--move
select 'alter index '||index_owner||'.'||index_name ||' rebuild partition '||partition_name || ' tablespace DWH_IND_TBS online;' from dba_ind_partitions
 where index_name in ('IDX_OGG_STMT_ENTRY_ACC')
and index_owner ='T24REP'
and partition_name in ('SYS_P330847','SYS_P335803','SYS_P339763')

ALTER TABLE T24REP.OGG_STMT_ENTRY MOVE PARTITION SYS_P330847 TABLESPACE T24REP_TBS PARALLEL 4;
alter index T24REP.IDX_OGG_STMT_ENTRY_ACC rebuild partition SYS_P330847 tablespace DWH_IND_TBS online;
alter index T24REP.PK_OGG_STMT_ENTRY_ID_N rebuild partition SYS_P330847 tablespace DWH_IND_TBS online;

ALTER TABLE T24REP.OGG_STMT_ENTRY MOVE PARTITION SYS_P335803 TABLESPACE T24REP_TBS PARALLEL 4;
alter index T24REP.IDX_OGG_STMT_ENTRY_ACC rebuild partition SYS_P335803 tablespace DWH_IND_TBS online;
alter index T24REP.PK_OGG_STMT_ENTRY_ID_N rebuild partition SYS_P335803 tablespace DWH_IND_TBS online;

ALTER TABLE T24REP.OGG_STMT_ENTRY MOVE PARTITION SYS_P339763 TABLESPACE T24REP_TBS PARALLEL 4;
alter index T24REP.IDX_OGG_STMT_ENTRY_ACC rebuild partition SYS_P339763 tablespace DWH_IND_TBS online;
alter index T24REP.PK_OGG_STMT_ENTRY_ID_N rebuild partition SYS_P339763 tablespace DWH_IND_TBS online;


-------------###main
/*
  CREATE UNIQUE INDEX "T24LIVE"."FBNK_STMT_ENTRY_PAR_PK_NEW" ON "T24LIVE"."FBNK_STMT_ENTRY" ("RECID",'1') LOCAL ONLINE 
  TABLESPACE "DATAT24LIVE" parallel 24;
--Elapsed: 00:37:49.31
--Elapsed: 00:41:39.87
--Elapsed: 00:51:57.07
--new Elapsed: 00:46:26.01

  ALTER TABLE T24LIVE.FBNK_STMT_ENTRY Drop CONSTRAINT FBNK_STMT_ENTRY_PARTITION_PK  ;
  
  drop index T24LIVE.FBNK_STMT_ENTRY_PARTITION_PK;

  CREATE UNIQUE INDEX "T24LIVE"."FBNK_STMT_ENTRY_PARTITION_PK" ON "T24LIVE"."FBNK_STMT_ENTRY" ("RECID") LOCAL ONLINE 
  TABLESPACE "INDEXT24LIVE" parallel 24;
  
--Elapsed: 00:43:38.21  
--Elapsed: 00:50:56.70
--new Elapsed: 00:48:44.02
  ALTER TABLE T24LIVE.FBNK_STMT_ENTRY ADD (
  CONSTRAINT FBNK_STMT_ENTRY_PARTITION_PK
  PRIMARY KEY
  (RECID)
  USING INDEX T24LIVE.FBNK_STMT_ENTRY_PARTITION_PK
  ENABLE NOVALIDATE);
  
  alter index T24LIVE.FBNK_STMT_ENTRY_PARTITION_PK noparallel;


  drop index T24LIVE.FBNK_STMT_ENTRY_PAR_PK_NEW;

BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24LIVE'
     ,IndName        => 'FBNK_STMT_ENTRY_PARTITION_PK'
     ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	 ,Degree          => 24);
END;
/
*/
----===================================================
-------------------------------------------------------
--table3
/*
  CREATE UNIQUE INDEX "T24LIVE"."FBNK_RE_C017_PAR_PK_NEW" ON "T24LIVE"."FBNK_RE_C017" ("RECID",'1') LOCAL ONLINE 
  TABLESPACE "DATAT24LIVE" parallel 24;
--
--Elapsed: 00:07:23.39

ALTER TABLE T24LIVE.FBNK_RE_C017 drop   CONSTRAINT FBNK_RE_C017_PARTITION_PK ;
 
  drop index T24LIVE.FBNK_RE_C017_PARTITION_PK;

  CREATE UNIQUE INDEX "T24LIVE"."FBNK_RE_C017_PARTITION_PK" ON "T24LIVE"."FBNK_RE_C017" ("RECID") LOCAL ONLINE 
  TABLESPACE "INDEXT24LIVE" parallel 24;
--Elapsed: 00:10:32.94
--Elapsed: 00:10:53.72

ALTER TABLE T24LIVE.FBNK_RE_C017 ADD (
  CONSTRAINT FBNK_RE_C017_PARTITION_PK
  PRIMARY KEY
  (RECID)
  USING INDEX T24LIVE.FBNK_RE_C017_PARTITION_PK
  ENABLE NOVALIDATE); 
  
  alter index T24LIVE.FBNK_RE_C017_PARTITION_PK noparallel;

  drop index T24LIVE.FBNK_RE_C017_PAR_PK_NEW;

  BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24LIVE'
     ,IndName        => 'FBNK_RE_C017_PARTITION_PK'
     ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	 ,Degree          => 24);
END;
/

*/
--Elapsed: 00:02:04.00

-------------------------------------------------------
--table4
/*
  CREATE UNIQUE INDEX "T24LIVE"."FBNK_CATEG_ENTRY_PAR_PK_NEW" ON "T24LIVE"."FBNK_CATEG_ENTRY" ("RECID",'1') LOCAL ONLINE 
  TABLESPACE "DATAT24LIVE" parallel 24;
--Elapsed: 00:10:50.07
--Elapsed: 00:11:26.84
  ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY drop CONSTRAINT FBNK_CATEG_ENTRY_PARTITION_PK;

  drop index T24LIVE.FBNK_CATEG_ENTRY_PARTITION_PK;

  CREATE UNIQUE INDEX "T24LIVE"."FBNK_CATEG_ENTRY_PARTITION_PK" ON "T24LIVE"."FBNK_CATEG_ENTRY" ("RECID") LOCAL ONLINE 
  TABLESPACE "INDEXT24LIVE" parallel 24;
--Elapsed: 00:14:08.92
--Elapsed: 00:07:20.68
  ALTER TABLE T24LIVE.FBNK_CATEG_ENTRY ADD (
  CONSTRAINT FBNK_CATEG_ENTRY_PARTITION_PK
  PRIMARY KEY
  (RECID)
  USING INDEX T24LIVE.FBNK_CATEG_ENTRY_PARTITION_PK
  ENABLE NOVALIDATE);

  alter index T24LIVE.FBNK_CATEG_ENTRY_PARTITION_PK noparallel;

  drop index T24LIVE.FBNK_CATEG_ENTRY_PAR_PK_NEW;

  BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24LIVE'
     ,IndName        => 'FBNK_CATEG_ENTRY_PARTITION_PK'
     ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	 ,Degree          => 24);
END;
/

*/
--table5
  /*
  --CREATE UNIQUE INDEX "T24LIVE"."FBNK_FUNDS_TRANHIS_PAR_PK_NEW" ON "T24LIVE"."FBNK_FUNDS_TRANSFER#HIS" ("RECID",'1') LOCAL ONLINE 
  TABLESPACE "DATAT24LIVE" parallel 28;
--Elapsed: 00:07:07.55
--Elapsed: 00:07:45.60

  ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS Drop CONSTRAINT FBNK_FUNDS_TRANSFER#HIS_PAR_PK;

  drop index T24LIVE.FBNK_FUNDS_TRANSFER#HIS_PAR_PK;

  CREATE UNIQUE INDEX "T24LIVE"."FBNK_FUNDS_TRANSFER#HIS_PAR_PK" ON "T24LIVE"."FBNK_FUNDS_TRANSFER#HIS" ("RECID") LOCAL ONLINE 
  TABLESPACE "INDEXT24LIVE" parallel 28;
--Elapsed: 00:08:33.30
--Elapsed: 00:06:23.40

  ALTER TABLE T24LIVE.FBNK_FUNDS_TRANSFER#HIS ADD (
  CONSTRAINT FBNK_FUNDS_TRANSFER#HIS_PAR_PK
  PRIMARY KEY
  (RECID)
  USING INDEX T24LIVE.FBNK_FUNDS_TRANSFER#HIS_PAR_PK
  ENABLE NOVALIDATE);

  
  alter index T24LIVE.FBNK_FUNDS_TRANSFER#HIS_PAR_PK noparallel;


  drop index T24LIVE.FBNK_FUNDS_TRANHIS_PAR_PK_NEW;

  BEGIN
  SYS.DBMS_STATS.GATHER_INDEX_STATS (
      OwnName        => 'T24LIVE'
     ,IndName        => 'FBNK_FUNDS_TRANSFER#HIS_PAR_PK'
     ,Estimate_Percent  => DBMS_STATS.AUTO_SAMPLE_SIZE
	 ,Degree          => 28);
END;
/

*/





--------------------split  9zfk3a7jdaant
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX       AT ('17930') INTO (PARTITION STMT_ENTRY_P1701,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1  AT ('17958') INTO (PARTITION STMT_ENTRY_P1702,PARTITION STMT_ENTRY_PMAX_TMP2) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP2  AT ('17989') INTO (PARTITION STMT_ENTRY_P1703,PARTITION STMT_ENTRY_PMAX_TMP3) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP3  AT ('18019') INTO (PARTITION STMT_ENTRY_P1704,PARTITION STMT_ENTRY_PMAX_TMP4) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP4  AT ('18050') INTO (PARTITION STMT_ENTRY_P1705,PARTITION STMT_ENTRY_PMAX_TMP5) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP5  AT ('18080') INTO (PARTITION STMT_ENTRY_P1706,PARTITION STMT_ENTRY_PMAX_TMP6) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP6  AT ('18111') INTO (PARTITION STMT_ENTRY_P1707,PARTITION STMT_ENTRY_PMAX_TMP7) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP7  AT ('18142') INTO (PARTITION STMT_ENTRY_P1708,PARTITION STMT_ENTRY_PMAX_TMP8) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP8  AT ('18172') INTO (PARTITION STMT_ENTRY_P1709,PARTITION STMT_ENTRY_PMAX_TMP9) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP9  AT ('18203') INTO (PARTITION STMT_ENTRY_P1710,PARTITION STMT_ENTRY_PMAX_TMP10) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP10 AT ('18233') INTO (PARTITION STMT_ENTRY_P1711,PARTITION STMT_ENTRY_PMAX_TMP11) UPDATE GLOBAL  INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP11 AT ('18264') INTO (PARTITION STMT_ENTRY_P1712,PARTITION STMT_ENTRY_PMAX) UPDATE GLOBAL  INDEXES;
select count(*) from T24LIVE.FBNK_STMT_ENTRY where recid > '18080'--STMT_ENTRY_P1706
--902510

select count(*) from T24LIVE.FBNK_STMT_ENTRY where recid > '18050'--STMT_ENTRY_P1705
--902510

select count(*) from T24LIVE.FBNK_STMT_ENTRY where recid > '18019' --STMT_ENTRY_P1704
--902510

select count(*) from T24LIVE.FBNK_STMT_ENTRY where recid > '17989'--STMT_ENTRY_P1703
--16254223
SQL> ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18415') 
  2  INTO (PARTITION STMT_ENTRY_P1805,PARTITION STMT_ENTRY_PMAX_TMP5) UPDATE   INDEXES parallel 24;

Table altered.

Elapsed: 05:18:34.20
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('18295')      INTO (PARTITION STMT_ENTRY_P1801,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18323') INTO (PARTITION STMT_ENTRY_P1802,PARTITION STMT_ENTRY_PMAX_TMP2) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP2 AT ('18354') INTO (PARTITION STMT_ENTRY_P1803,PARTITION STMT_ENTRY_PMAX_TMP3) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP3 AT ('18384') INTO (PARTITION STMT_ENTRY_P1804,PARTITION STMT_ENTRY_PMAX_TMP4) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP4 AT ('18415') INTO (PARTITION STMT_ENTRY_P1805,PARTITION STMT_ENTRY_PMAX_TMP5) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP5 AT ('18445') INTO (PARTITION STMT_ENTRY_P1806,PARTITION STMT_ENTRY_PMAX_TMP6) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP6 AT ('18476') INTO (PARTITION STMT_ENTRY_P1807,PARTITION STMT_ENTRY_PMAX_TMP7) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP7 AT ('18507') INTO (PARTITION STMT_ENTRY_P1808,PARTITION STMT_ENTRY_PMAX_TMP8) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP8 AT ('18537') INTO (PARTITION STMT_ENTRY_P1809,PARTITION STMT_ENTRY_PMAX_TMP9) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP9 AT ('18568') INTO (PARTITION STMT_ENTRY_P1810,PARTITION STMT_ENTRY_PMAX_TMP10) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP10 AT ('18598') INTO (PARTITION STMT_ENTRY_P1811,PARTITION STMT_ENTRY_PMAX_TMP11) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP11 AT ('18629') INTO (PARTITION STMT_ENTRY_P1812,PARTITION STMT_ENTRY_PMAX) UPDATE   INDEXES parallel 24;

ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('18660') INTO (PARTITION STMT_ENTRY_P1901,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE   INDEXES;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('18688') INTO (PARTITION STMT_ENTRY_P1902,PARTITION STMT_ENTRY_PMAX_TMP2) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP2 AT ('18719') INTO (PARTITION STMT_ENTRY_P1903,PARTITION STMT_ENTRY_PMAX_TMP3) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP3 AT ('18749') INTO (PARTITION STMT_ENTRY_P1904,PARTITION STMT_ENTRY_PMAX_TMP4) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP4 AT ('18780') INTO (PARTITION STMT_ENTRY_P1905,PARTITION STMT_ENTRY_PMAX_TMP5) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP5 AT ('18810') INTO (PARTITION STMT_ENTRY_P1906,PARTITION STMT_ENTRY_PMAX_TMP6) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP6 AT ('18841') INTO (PARTITION STMT_ENTRY_P1907,PARTITION STMT_ENTRY_PMAX_TMP7) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP7 AT ('18872') INTO (PARTITION STMT_ENTRY_P1908,PARTITION STMT_ENTRY_PMAX_TMP8) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP8 AT ('18902') INTO (PARTITION STMT_ENTRY_P1909,PARTITION STMT_ENTRY_PMAX_TMP9) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP9 AT ('18933') INTO (PARTITION STMT_ENTRY_P1910,PARTITION STMT_ENTRY_PMAX_TMP10) UPDATE INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP10 AT ('18963') INTO (PARTITION STMT_ENTRY_P1911,PARTITION STMT_ENTRY_PMAX_TMP11) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP11 AT ('18994') INTO (PARTITION STMT_ENTRY_P1912,PARTITION STMT_ENTRY_PMAX) UPDATE   INDEXES parallel 24;

ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX AT ('19025') INTO (PARTITION STMT_ENTRY_P2001,PARTITION STMT_ENTRY_PMAX_TMP1) UPDATE        INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP1 AT ('19054') INTO (PARTITION STMT_ENTRY_P2002,PARTITION STMT_ENTRY_PMAX_TMP2) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP2 AT ('19085') INTO (PARTITION STMT_ENTRY_P2003,PARTITION STMT_ENTRY_PMAX_TMP3) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP3 AT ('19115') INTO (PARTITION STMT_ENTRY_P2004,PARTITION STMT_ENTRY_PMAX_TMP4) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP4 AT ('19146') INTO (PARTITION STMT_ENTRY_P2005,PARTITION STMT_ENTRY_PMAX_TMP5) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP5 AT ('19176') INTO (PARTITION STMT_ENTRY_P2006,PARTITION STMT_ENTRY_PMAX_TMP6) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP6 AT ('19207') INTO (PARTITION STMT_ENTRY_P2007,PARTITION STMT_ENTRY_PMAX_TMP7) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP7 AT ('19238') INTO (PARTITION STMT_ENTRY_P2008,PARTITION STMT_ENTRY_PMAX_TMP8) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP8 AT ('19268') INTO (PARTITION STMT_ENTRY_P2009,PARTITION STMT_ENTRY_PMAX_TMP9) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP9 AT ('19299') INTO (PARTITION STMT_ENTRY_P2010,PARTITION STMT_ENTRY_PMAX_TMP10) UPDATE  INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP10 AT ('19329') INTO (PARTITION STMT_ENTRY_P2011,PARTITION STMT_ENTRY_PMAX_TMP11) UPDATE   INDEXES parallel 24;
ALTER TABLE T24LIVE.FBNK_STMT_ENTRY SPLIT PARTITION STMT_ENTRY_PMAX_TMP11 AT ('19360') INTO (PARTITION STMT_ENTRY_P2012,PARTITION STMT_ENTRY_PMAX) UPDATE   INDEXES parallel 24;

--------------------end split