DONE---/DIRECTORY/DIRECTORY
---/DIRECTORY/GRANT/OWNER_GRANT/OBJECT_GRANT
DONE---/TABLESPACE
DONE---/PROFILE
NO NEED??---/PASSWORD_VERIFY_FUNCTION
NO NEED---/SYS_USER/USER 
DONE---/SCHEMA/USER
---/ROLE
---/GRANT/SYSTEM_GRANT/PROC_SYSTEM_GRANT
---/SCHEMA/GRANT/SYSTEM_GRANT
---/SCHEMA/ROLE_GRANT
---/SCHEMA/DEFAULT_ROLE
NO NEED---/PROXY  
NO NEED---/SCHEMA/TABLESPACE_QUOTA

??---/SCHEMA/PUBLIC_SYNONYM/SYNONYM
??---/SCHEMA/SYNONYM

---/RESOURCE_COST
---/TRUSTED_DB_LINK -->NO
---/SCHEMA/SEQUENCE/SEQUENCE
---/SCHEMA/SEQUENCE/GRANT/OWNER_GRANT/OBJECT_GRANT
---/CONTEXT
---/SCHEMA/TYPE/TYPE_SPEC
---/SCHEMA/TYPE/GRANT/OWNER_GRANT/OBJECT_GRANT
---/SYSTEM_PROCOBJACT/PRE_SYSTEM_ACTIONS/PROCACT_SYSTEM
---/SYSTEM_PROCOBJACT/PROCOBJ
---/SYSTEM_PROCOBJACT/POST_SYSTEM_ACTIONS/PROCACT_SYSTEM
---/SCHEMA/PROCACT_SCHEMA
---/SCHEMA/TABLE/PROCACT_INSTANCE
---/SCHEMA/TABLE/TABLE
---/SCHEMA/TABLE/GRANT/OWNER_GRANT/OBJECT_GRANT
---/SCHEMA/TABLE/COMMENT
---/SCHEMA/PACKAGE/PACKAGE_SPEC
---/SCHEMA/PACKAGE/GRANT/OWNER_GRANT/OBJECT_GRANT
---/SCHEMA/FUNCTION/FUNCTION
---/SCHEMA/FUNCTION/GRANT/OWNER_GRANT/OBJECT_GRANT
---/SCHEMA/PROCEDURE/PROCEDURE
---/SCHEMA/PROCEDURE/GRANT/OWNER_GRANT/OBJECT_GRANT
---/SCHEMA/FUNCTION/ALTER_FUNCTION
---/SCHEMA/PROCEDURE/ALTER_PROCEDURE
---/SCHEMA/TABLE/INDEX/INDEX
---/SCHEMA/TABLE/INDEX/FUNCTIONAL_INDEX/INDEX
---/SCHEMA/TABLE/CONSTRAINT/CONSTRAINT
---/SCHEMA/VIEW/VIEW
---/SCHEMA/VIEW/GRANT/OWNER_GRANT/OBJECT_GRANT
---/SCHEMA/VIEW/COMMENT
---/SCHEMA/PACKAGE_BODIES/PACKAGE/PACKAGE_BODY
---/SCHEMA/TABLE/CONSTRAINT/REF_CONSTRAINT
---/SCHEMA/TABLE/TRIGGER
---/SCHEMA/MATERIALIZED_VIEW
---/SCHEMA/JOB
---/SCHEMA/TABLE/POST_INSTANCE/PROCACT_INSTANCE
---/SCHEMA/TABLE/POST_INSTANCE/PROCDEPOBJ
---/SCHEMA/POST_SCHEMA/PROCOBJ
---/SCHEMA/POST_SCHEMA/PROCACT_SCHEMA
---/SCHEMA/PASSWORD_HISTORY
---/AUDIT



 expdp DIRECTORY=YEAREND Schemas=t24live,t24_live_dwh CONTENT=METADATA_ONLY dumpfile=metadata.dmp logfile=metadata.log exclude=statistics  parallel=4
 
 expdp DIRECTORY=YEAREND FULL=Y CONTENT=METADATA_ONLY dumpfile=metadata.dmp logfile=metadata.log exclude=statistics  parallel=4
 
 impdp DIRECTORY=YEAREND dumpfile=metadata.dmp logfile=imp_metadata.log
 
 expdp DIRECTORY=YEAREND Schemas=t24live,t24_live_dwh CONTENT=DATA_ONLY dumpfile=data%u.dmp logfile=exp_data.log parallel=4 filesize=10G
 
 
 --create db year18
 dbca -silent \
-createDatabase \
-templateName General_Purpose.dbc \
-gdbName year18 \
-sid year18 \
-SysPassword db#Chivas#123 \
-SystemPassword db#Chivas#123 \
-emConfiguration NONE \
-redoLogFileSize 4096 \
-storageType ASM \
-asmSysPassword db#Chivas#123 \
-diskGroupName YEAREND_DR \
-recoveryAreaDestination YEAREND_DR \
-characterSet AL32UTF8 \
-nationalCharacterSet AL16UTF16 \
-totalMemory 10240

-> pfile 

shutdown immediate;
startup mount;
alter database archivelog;


run script: create tbs, profile, user

-->    dbca -silent -deleteDatabase -sourceDB year18 -sysDBAUserName sys -sysDBAPassword db#Chivas#123
 
 --create directories on year18 and monthend
 create directory YEAREND as '/testcob/year18';
 
 
 ---export monthend
 expdp DIRECTORY=YEAREND Schemas=t24live dumpfile=remain%u.dmp logfile=remain.log exclude=statistics,index  parallel=4  exclude=TABLE:\"IN\(\'FBNK_STMT_PRINTED\',\'FBNK_STMT_ENTRY\',\'F_ENQUIRY_SELECT\',\'FBNK_ACCOUNT\',\'FBNK_MM_M000\',\'FBNK_PM_TRAN_ACTIVITY\',\'FBNK_FUNDS_TRANSFER#HIS\',\'FBNK_STMT_ACCT_CR\',\'FBNK_AI_USER_LOG\',\'FBNK_RE_C018\',\'FBNK_EB_C005\',\'FBNK_CATEG_ENTRY\',\'FBNK_ACCT_ACTIVITY\',\'FBNK_DEPO_WITHDRA\',\'FBNK_RE_CONSOL_PROFIT\',\'FBNK_RE_C017\',\'F_ATM_REVERSAL\',\'FBNK_RE_C019\',\'F_DC_NEW_003\',\'F_DE_O_HANDOFF\',\'FBNK_ACCOUNT#HIS\',\'F_ENQUIRY_SELECT_INI\',\'FBNK_INFO_CARD\'\)\"
 
 impdp DIRECTORY=YEAREND dumpfile=remain%u.dmp logfile=imp_remain.log parallel=4 
 
 expdp DIRECTORY=YEAREND dumpfile=big_table%u.dmp logfile=big_table.log exclude=statistics,index  parallel=12  tables=T24LIVE.FBNK_STMT_PRINTED,T24LIVE.FBNK_STMT_ENTRY,T24LIVE.F_ENQUIRY_SELECT,T24LIVE.FBNK_ACCOUNT,T24LIVE.FBNK_MM_M000,T24LIVE.FBNK_PM_TRAN_ACTIVITY,T24LIVE.FBNK_FUNDS_TRANSFER#HIS,T24LIVE.FBNK_STMT_ACCT_CR,T24LIVE.FBNK_AI_USER_LOG,T24LIVE.FBNK_RE_C018,T24LIVE.FBNK_EB_C005,T24LIVE.FBNK_CATEG_ENTRY,T24LIVE.FBNK_ACCT_ACTIVITY,T24LIVE.FBNK_DEPO_WITHDRA,T24LIVE.FBNK_RE_CONSOL_PROFIT,T24LIVE.FBNK_RE_C017,T24LIVE.F_ATM_REVERSAL,T24LIVE.FBNK_RE_C019,T24LIVE.F_DC_NEW_003,T24LIVE.F_DE_O_HANDOFF,T24LIVE.FBNK_ACCOUNT#HIS,T24LIVE.F_ENQUIRY_SELECT_INI,T24LIVE.FBNK_INFO_CARD