CREATE TABLESPACE DATAT24LIVE DATAFILE 
  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE DATAT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;

CREATE TABLESPACE HOMEBANKING_TBS DATAFILE 
  '+YEAREND_DR' SIZE 32758M AUTOEXTEND OFF
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE INDEXT24LIVE DATAFILE 
  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE INDEXT24LIVE ADD DATAFILE  '+YEAREND_DR' SIZE 32767M AUTOEXTEND OFF;

CREATE TEMPORARY TABLESPACE TEMP_NEW TEMPFILE 
  '+YEAREND_DR' SIZE 30G AUTOEXTEND OFF,
  '+YEAREND_DR' SIZE 30G AUTOEXTEND OFF,
  '+YEAREND_DR' SIZE 30G AUTOEXTEND OFF
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE TEMPORARY TABLESPACE TEMPT24LIVE TEMPFILE 
  '+YEAREND_DR' SIZE 30G AUTOEXTEND OFF,
  '+YEAREND_DR' SIZE 30G AUTOEXTEND OFF,
  '+YEAREND_DR' SIZE 30G AUTOEXTEND OFF
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 4M;

--ora verify function
CREATE OR REPLACE FUNCTION "SYS"."ORA_VERIFY_FUNCTION"
(username varchar2,
 password varchar2,
 old_password varchar2)
RETURN boolean IS
   differ integer;
   db_name varchar2(40);
   i integer;
BEGIN
   IF NOT ora_complexity_check(password, chars => 12, upper => 1, lower => 1, digit => 1, special => 1) THEN
      RETURN(FALSE);
   END IF;

   -- Check if the password contains the server name
   select name into db_name from sys.v$database;
   IF regexp_instr(password, db_name, 1, 1, 0, 'i') > 0 THEN
      raise_application_error(-20004, 'Password contains the server name');
   END IF;

   -- Check if the password contains 'oracle'
   IF regexp_instr(password, 'oracle', 1, 1, 0, 'i') > 0 THEN
        raise_application_error(-20006, 'Password too simple');
   END IF;

   -- Check if the password differs from the previous password by at least
   -- 3 characters
   IF old_password IS NOT NULL THEN
     differ := ora_string_distance(old_password, password);
     IF differ < 3 THEN
        raise_application_error(-20010, 'Password should differ from the '
                                || 'old password by at least 3 characters');
     END IF;
   END IF ;

   RETURN(TRUE);
END;
/

GRANT EXECUTE ON ORA_VERIFY_FUNCTION TO PUBLIC;
GRANT EXECUTE ON ORA_COMPLEXITY_CHECK TO PUBLIC;
GRANT EXECUTE ON ORA_STRING_DISTANCE TO PUBLIC;


--profile
CREATE PROFILE DBA_PROFILE LIMIT
  SESSIONS_PER_USER DEFAULT
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME DEFAULT
  PASSWORD_REUSE_MAX DEFAULT
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME DEFAULT
  PASSWORD_VERIFY_FUNCTION ORA_VERIFY_FUNCTION;

  CREATE PROFILE PROFILE_SERVICE_ACCOUNT LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS UNLIMITED
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME DEFAULT
  PASSWORD_REUSE_MAX DEFAULT
  PASSWORD_LOCK_TIME DEFAULT
  PASSWORD_GRACE_TIME DEFAULT
  PASSWORD_VERIFY_FUNCTION ORA_VERIFY_FUNCTION;

CREATE PROFILE PROFILE_ENDUSER LIMIT
  SESSIONS_PER_USER 10
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 60
  PASSWORD_REUSE_TIME 240
  PASSWORD_REUSE_MAX 4
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME 10
  PASSWORD_VERIFY_FUNCTION ORA_VERIFY_FUNCTION;

CREATE PROFILE MONITORING_PROFILE LIMIT
  SESSIONS_PER_USER DEFAULT
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME DEFAULT
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS UNLIMITED
  PASSWORD_LIFE_TIME DEFAULT
  PASSWORD_REUSE_TIME DEFAULT
  PASSWORD_REUSE_MAX DEFAULT
  PASSWORD_LOCK_TIME DEFAULT
  PASSWORD_GRACE_TIME DEFAULT
  PASSWORD_VERIFY_FUNCTION DEFAULT;  
 
--create directory
SELECT DBMS_METADATA.get_ddl ('DIRECTORY', directory_name)||';'
FROM   dba_directories;

 
--=Create user
CREATE USER T24LIVE
  IDENTIFIED BY Qwerty#12345
  DEFAULT TABLESPACE DATAT24LIVE
  TEMPORARY TABLESPACE TEMPT24LIVE
  PROFILE PROFILE_SERVICE_ACCOUNT
  ACCOUNT UNLOCK;
  -- 5 Roles for T24LIVE 
  GRANT CONNECT TO T24LIVE;
  GRANT EXP_FULL_DATABASE TO T24LIVE;
  GRANT IMP_FULL_DATABASE TO T24LIVE;
  GRANT RESOURCE TO T24LIVE;
  GRANT SQLT_USER_ROLE TO T24LIVE;
  ALTER USER T24LIVE DEFAULT ROLE ALL;
  -- 203 System Privileges for T24LIVE 
  GRANT ADMINISTER ANY SQL TUNING SET TO T24LIVE;
  GRANT ADMINISTER DATABASE TRIGGER TO T24LIVE;
  BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'T24LIVE', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO T24LIVE;
  GRANT ADMINISTER SQL TUNING SET TO T24LIVE;
  GRANT ADVISOR TO T24LIVE;
  GRANT ALTER ANY ASSEMBLY TO T24LIVE;
  GRANT ALTER ANY CLUSTER TO T24LIVE;
  GRANT ALTER ANY CUBE TO T24LIVE;
  GRANT ALTER ANY CUBE DIMENSION TO T24LIVE;
  GRANT ALTER ANY DIMENSION TO T24LIVE;
  GRANT ALTER ANY EDITION TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT ALTER ANY INDEX TO T24LIVE;
  GRANT ALTER ANY INDEXTYPE TO T24LIVE;
  GRANT ALTER ANY LIBRARY TO T24LIVE;
  GRANT ALTER ANY MATERIALIZED VIEW TO T24LIVE;
  GRANT ALTER ANY MINING MODEL TO T24LIVE;
  GRANT ALTER ANY OPERATOR TO T24LIVE;
  GRANT ALTER ANY OUTLINE TO T24LIVE;
  GRANT ALTER ANY PROCEDURE TO T24LIVE;
  GRANT ALTER ANY ROLE TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT ALTER ANY SEQUENCE TO T24LIVE;
  GRANT ALTER ANY SQL PROFILE TO T24LIVE;
  GRANT ALTER ANY TABLE TO T24LIVE;
  GRANT ALTER ANY TRIGGER TO T24LIVE;
  GRANT ALTER ANY TYPE TO T24LIVE;
  GRANT ALTER DATABASE TO T24LIVE;
  GRANT ALTER PROFILE TO T24LIVE;
  GRANT ALTER RESOURCE COST TO T24LIVE;
  GRANT ALTER ROLLBACK SEGMENT TO T24LIVE;
  GRANT ALTER SESSION TO T24LIVE;
  GRANT ALTER SYSTEM TO T24LIVE;
  GRANT ALTER TABLESPACE TO T24LIVE;
  GRANT ALTER USER TO T24LIVE;
  GRANT ANALYZE ANY TO T24LIVE;
  GRANT AUDIT ANY TO T24LIVE;
  GRANT AUDIT SYSTEM TO T24LIVE;
  GRANT BACKUP ANY TABLE TO T24LIVE;
  GRANT BECOME USER TO T24LIVE;
  GRANT CHANGE NOTIFICATION TO T24LIVE;
  GRANT COMMENT ANY MINING MODEL TO T24LIVE;
  GRANT COMMENT ANY TABLE TO T24LIVE;
  GRANT CREATE ANY ASSEMBLY TO T24LIVE;
  GRANT CREATE ANY CLUSTER TO T24LIVE;
  GRANT CREATE ANY CONTEXT TO T24LIVE;
  GRANT CREATE ANY CREDENTIAL TO T24LIVE;
  GRANT CREATE ANY CUBE TO T24LIVE;
  GRANT CREATE ANY CUBE BUILD PROCESS TO T24LIVE;
  GRANT CREATE ANY CUBE DIMENSION TO T24LIVE;
  GRANT CREATE ANY DIMENSION TO T24LIVE;
  GRANT CREATE ANY DIRECTORY TO T24LIVE;
  GRANT CREATE ANY EDITION TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE ANY INDEX TO T24LIVE;
  GRANT CREATE ANY INDEXTYPE TO T24LIVE;
  GRANT CREATE ANY JOB TO T24LIVE;
  GRANT CREATE ANY LIBRARY TO T24LIVE;
  GRANT CREATE ANY MATERIALIZED VIEW TO T24LIVE;
  GRANT CREATE ANY MEASURE FOLDER TO T24LIVE;
  GRANT CREATE ANY MINING MODEL TO T24LIVE;
  GRANT CREATE ANY OPERATOR TO T24LIVE;
  GRANT CREATE ANY OUTLINE TO T24LIVE;
  GRANT CREATE ANY PROCEDURE TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE ANY SEQUENCE TO T24LIVE;
  GRANT CREATE ANY SQL PROFILE TO T24LIVE;
  GRANT CREATE ANY SYNONYM TO T24LIVE;
  GRANT CREATE ANY TABLE TO T24LIVE;
  GRANT CREATE ANY TRIGGER TO T24LIVE;
  GRANT CREATE ANY TYPE TO T24LIVE;
  GRANT CREATE ANY VIEW TO T24LIVE;
  GRANT CREATE ASSEMBLY TO T24LIVE;
  GRANT CREATE CLUSTER TO T24LIVE;
  GRANT CREATE CREDENTIAL TO T24LIVE;
  GRANT CREATE CUBE TO T24LIVE;
  GRANT CREATE CUBE BUILD PROCESS TO T24LIVE;
  GRANT CREATE CUBE DIMENSION TO T24LIVE;
  GRANT CREATE DATABASE LINK TO T24LIVE;
  GRANT CREATE DIMENSION TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE EXTERNAL JOB TO T24LIVE;
  GRANT CREATE INDEXTYPE TO T24LIVE;
  GRANT CREATE JOB TO T24LIVE;
  GRANT CREATE LIBRARY TO T24LIVE;
  GRANT CREATE MATERIALIZED VIEW TO T24LIVE;
  GRANT CREATE MEASURE FOLDER TO T24LIVE;
  GRANT CREATE MINING MODEL TO T24LIVE;
  GRANT CREATE OPERATOR TO T24LIVE;
  GRANT CREATE PROCEDURE TO T24LIVE;
  GRANT CREATE PROFILE TO T24LIVE;
  GRANT CREATE PUBLIC DATABASE LINK TO T24LIVE;
  GRANT CREATE PUBLIC SYNONYM TO T24LIVE;
  GRANT CREATE ROLE TO T24LIVE;
  GRANT CREATE ROLLBACK SEGMENT TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT CREATE SEQUENCE TO T24LIVE;
  GRANT CREATE SESSION TO T24LIVE;
  GRANT CREATE SYNONYM TO T24LIVE;
  GRANT CREATE TABLE TO T24LIVE;
  GRANT CREATE TABLESPACE TO T24LIVE;
  GRANT CREATE TRIGGER TO T24LIVE;
  GRANT CREATE TYPE TO T24LIVE;
  GRANT CREATE USER TO T24LIVE;
  GRANT CREATE VIEW TO T24LIVE;
  GRANT DEBUG ANY PROCEDURE TO T24LIVE;
  GRANT DEBUG CONNECT SESSION TO T24LIVE;
  GRANT DELETE ANY CUBE DIMENSION TO T24LIVE;
  GRANT DELETE ANY MEASURE FOLDER TO T24LIVE;
  GRANT DELETE ANY TABLE TO T24LIVE;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'T24LIVE',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT DROP ANY ASSEMBLY TO T24LIVE;
  GRANT DROP ANY CLUSTER TO T24LIVE;
  GRANT DROP ANY CONTEXT TO T24LIVE;
  GRANT DROP ANY CUBE TO T24LIVE;
  GRANT DROP ANY CUBE BUILD PROCESS TO T24LIVE;
  GRANT DROP ANY CUBE DIMENSION TO T24LIVE;
  GRANT DROP ANY DIMENSION TO T24LIVE;
  GRANT DROP ANY DIRECTORY TO T24LIVE;
  GRANT DROP ANY EDITION TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT DROP ANY INDEX TO T24LIVE;
  GRANT DROP ANY INDEXTYPE TO T24LIVE;
  GRANT DROP ANY LIBRARY TO T24LIVE;
  GRANT DROP ANY MATERIALIZED VIEW TO T24LIVE;
  GRANT DROP ANY MEASURE FOLDER TO T24LIVE;
  GRANT DROP ANY MINING MODEL TO T24LIVE;
  GRANT DROP ANY OPERATOR TO T24LIVE;
  GRANT DROP ANY OUTLINE TO T24LIVE;
  GRANT DROP ANY PROCEDURE TO T24LIVE;
  GRANT DROP ANY ROLE TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT DROP ANY SEQUENCE TO T24LIVE;
  GRANT DROP ANY SQL PROFILE TO T24LIVE;
  GRANT DROP ANY SYNONYM TO T24LIVE;
  GRANT DROP ANY TABLE TO T24LIVE;
  GRANT DROP ANY TRIGGER TO T24LIVE;
  GRANT DROP ANY TYPE TO T24LIVE;
  GRANT DROP ANY VIEW TO T24LIVE;
  GRANT DROP PROFILE TO T24LIVE;
  GRANT DROP PUBLIC DATABASE LINK TO T24LIVE;
  GRANT DROP PUBLIC SYNONYM TO T24LIVE;
  GRANT DROP ROLLBACK SEGMENT TO T24LIVE;
  GRANT DROP TABLESPACE TO T24LIVE;
  GRANT DROP USER TO T24LIVE;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'T24LIVE',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT EXECUTE ANY ASSEMBLY TO T24LIVE;
  GRANT EXECUTE ANY CLASS TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT EXECUTE ANY INDEXTYPE TO T24LIVE;
  GRANT EXECUTE ANY LIBRARY TO T24LIVE;
  GRANT EXECUTE ANY OPERATOR TO T24LIVE;
  GRANT EXECUTE ANY PROCEDURE TO T24LIVE;
  GRANT EXECUTE ANY PROGRAM TO T24LIVE;
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'T24LIVE',
  GRANT_OPTION => FALSE);
END;
/
  GRANT EXECUTE ANY TYPE TO T24LIVE;
  GRANT EXECUTE ASSEMBLY TO T24LIVE;
  GRANT EXPORT FULL DATABASE TO T24LIVE;
  GRANT FLASHBACK ANY TABLE TO T24LIVE;
  GRANT FLASHBACK ARCHIVE ADMINISTER TO T24LIVE;
  GRANT FORCE ANY TRANSACTION TO T24LIVE;
  GRANT FORCE TRANSACTION TO T24LIVE;
  GRANT GLOBAL QUERY REWRITE TO T24LIVE;
  GRANT GRANT ANY OBJECT PRIVILEGE TO T24LIVE;
  GRANT GRANT ANY PRIVILEGE TO T24LIVE;
  GRANT GRANT ANY ROLE TO T24LIVE;
  GRANT IMPORT FULL DATABASE TO T24LIVE;
  GRANT INSERT ANY CUBE DIMENSION TO T24LIVE;
  GRANT INSERT ANY MEASURE FOLDER TO T24LIVE;
  GRANT INSERT ANY TABLE TO T24LIVE;
  GRANT LOCK ANY TABLE TO T24LIVE;
  GRANT LOGMINING TO T24LIVE;
  GRANT MANAGE ANY FILE GROUP TO T24LIVE;
  BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'T24LIVE',
  ADMIN_OPTION => FALSE);
END;
/
  GRANT MANAGE FILE GROUP TO T24LIVE;
  GRANT MANAGE SCHEDULER TO T24LIVE;
  GRANT MANAGE TABLESPACE TO T24LIVE;
  GRANT MERGE ANY VIEW TO T24LIVE;
  GRANT ON COMMIT REFRESH TO T24LIVE;
  GRANT QUERY REWRITE TO T24LIVE;
  GRANT READ ANY FILE GROUP TO T24LIVE;
  GRANT RESTRICTED SESSION TO T24LIVE;
  GRANT RESUMABLE TO T24LIVE;
  GRANT SELECT ANY CUBE TO T24LIVE;
  GRANT SELECT ANY CUBE DIMENSION TO T24LIVE;
  GRANT SELECT ANY MINING MODEL TO T24LIVE;
  GRANT SELECT ANY SEQUENCE TO T24LIVE;
  GRANT SELECT ANY TABLE TO T24LIVE;
  GRANT SELECT ANY TRANSACTION TO T24LIVE;
  GRANT UNDER ANY TABLE TO T24LIVE;
  GRANT UNDER ANY TYPE TO T24LIVE;
  GRANT UNDER ANY VIEW TO T24LIVE;
  GRANT UNLIMITED TABLESPACE TO T24LIVE;
  GRANT UPDATE ANY CUBE TO T24LIVE;
  GRANT UPDATE ANY CUBE BUILD PROCESS TO T24LIVE;
  GRANT UPDATE ANY CUBE DIMENSION TO T24LIVE;
  GRANT UPDATE ANY TABLE TO T24LIVE;
  -- 2 Tablespace Quotas for T24LIVE 
  ALTER USER T24LIVE QUOTA UNLIMITED ON DATAT24LIVE;
  ALTER USER T24LIVE QUOTA UNLIMITED ON INDEXT24LIVE;
  -- 22 Object Privileges for T24LIVE 
    GRANT EXECUTE ON CTXSYS.DRITHSX TO T24LIVE;
    GRANT EXECUTE ON ORDSYS.ORD_DICOM TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_ADVISOR TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_AW_XML TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_JAVA TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_JOB TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_LDAP TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_LOCK TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_OBFUSCATION_TOOLKIT TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_RANDOM TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_SCHEDULER TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_SQL TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_XMLGEN TO T24LIVE;
    GRANT EXECUTE ON SYS.DBMS_XMLQUERY TO T24LIVE;
    GRANT EXECUTE ON SYS.HTTPURITYPE TO T24LIVE;
    GRANT EXECUTE, READ, WRITE ON DIRECTORY TRACE_DIR_SRC_4_TCB TO T24LIVE WITH GRANT OPTION;
    GRANT EXECUTE ON SYS.UTL_FILE TO T24LIVE;
    GRANT EXECUTE ON SYS.UTL_HTTP TO T24LIVE;
    GRANT EXECUTE ON SYS.UTL_INADDR TO T24LIVE;
    GRANT EXECUTE ON SYS.UTL_SMTP TO T24LIVE;
    GRANT EXECUTE ON SYS.UTL_TCP TO T24LIVE;
    GRANT SELECT ON SYS.V_$DATABASE TO T24LIVE;
  -- 2 Proxies for T24LIVE 
ALTER USER T24LIVE  GRANT CONNECT THROUGH THUYNTM_DBA;


CREATE USER T24_LIVE_DWH
  IDENTIFIED BY VALUES 'S:403EC2FB61CA45347C00BEC2D21E7336132E1CEA6D8EE7919D72C4AF6637;0902A6F715834F83'
  DEFAULT TABLESPACE HOMEBANKING_TBS
  TEMPORARY TABLESPACE TEMP_NEW
  PROFILE PROFILE_SERVICE_ACCOUNT
  ACCOUNT UNLOCK;
  -- 2 Roles for T24_LIVE_DWH 
  GRANT CONNECT TO T24_LIVE_DWH;
  GRANT RESOURCE TO T24_LIVE_DWH;
  ALTER USER T24_LIVE_DWH DEFAULT ROLE ALL;
  -- 3 System Privileges for T24_LIVE_DWH 
  GRANT CREATE ANY VIEW TO T24_LIVE_DWH;
  GRANT SELECT ANY TABLE TO T24_LIVE_DWH;
  GRANT UNLIMITED TABLESPACE TO T24_LIVE_DWH;
  -- 1 Tablespace Quota for T24_LIVE_DWH 
  ALTER USER T24_LIVE_DWH QUOTA UNLIMITED ON HOMEBANKING_TBS;
  -- 30 Object Privileges for T24_LIVE_DWH 
  
  
  --import
  
  --create index
  
  ---after import done
    GRANT EXECUTE ON CTXSYS.DRITHSX TO T24_LIVE_DWH;
    GRANT EXECUTE ON ORDSYS.ORD_DICOM TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_ADVISOR TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_AW_XML TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_JAVA TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_JOB TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_LDAP TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_OBFUSCATION_TOOLKIT TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_RANDOM TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_SCHEDULER TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_SQL TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_XMLGEN TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.DBMS_XMLQUERY TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.HTTPURITYPE TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.UTL_FILE TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.UTL_HTTP TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.UTL_INADDR TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.UTL_SMTP TO T24_LIVE_DWH;
    GRANT EXECUTE ON SYS.UTL_TCP TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_ACCOUNT TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_AC_CHARGE_REQUEST TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_CUSTOMER TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_FOREX TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_FUNDS_TRANSFER TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_LD_L000 TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_LETTER_OF_CREDIT TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_MD_DEAL TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_MM_M000 TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_TELLER TO T24_LIVE_DWH;
    GRANT SELECT ON T24LIVE.FBNK_TRANSACTION TO T24_LIVE_DWH;

  