set timing on
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'DWH',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'EDW_DMT',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'EDW_SOR',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'T24REP',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'T24REP',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'TCB_DWH_VAS',degree =>8,GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE);
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'KRM',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'KRM_APP',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
--EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname =>'KRM_RPT',degree =>8, GRANULARITY =>'AUTO',estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,CASCADE=>TRUE );
exit
